"""
PDF Report Generator
--------------------
Generates a downloadable PDF report with insights,
charts descriptions, and recommendations.
"""

from fpdf import FPDF
from pathlib import Path
from typing import Dict, Any, List
import textwrap
from datetime import datetime

from app.config import REPORTS_DIR


class StoryReportPDF(FPDF):
    """Custom PDF class with header and footer."""

    def __init__(self, title: str = "Data Analysis Report"):
        super().__init__()
        self.report_title = title
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, self.report_title, align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(99, 102, 241)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}} | Generated by Smart Data Storytelling Tool", align="C")

    def add_section_title(self, title: str):
        """Add a styled section title."""
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(99, 102, 241)
        self.ln(6)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(99, 102, 241)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 80, self.get_y())
        self.ln(4)

    def add_body_text(self, text: str):
        """Add body text with proper wrapping."""
        self.set_font("Helvetica", "", 10)
        self.set_text_color(50, 50, 50)
        # Clean and encode text for PDF compatibility
        safe_text = text.encode("latin-1", "replace").decode("latin-1")
        self.multi_cell(0, 6, safe_text)
        self.ln(3)

    def add_bullet_point(self, text: str, indent: int = 15):
        """Add a bullet point item."""
        self.set_font("Helvetica", "", 10)
        self.set_text_color(50, 50, 50)
        self.set_x(indent)
        safe_text = text.encode("latin-1", "replace").decode("latin-1")
        self.cell(5, 6, chr(149))  # bullet character
        self.multi_cell(0, 6, f" {safe_text}")
        self.ln(1)


def generate_pdf_report(
    title: str,
    story: Dict[str, Any],
    data_overview: Dict[str, Any],
    preprocessing_report: Dict[str, Any],
    session_id: str = "report",
) -> str:
    """
    Generate a PDF report from the analysis results.
    Returns the path to the generated PDF file.
    """
    pdf = StoryReportPDF(title=title)
    pdf.alias_nb_pages()
    pdf.add_page()

    # Title page
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(30, 30, 60)
    pdf.ln(30)
    safe_title = title.encode("latin-1", "replace").decode("latin-1")
    pdf.cell(0, 15, safe_title, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Dataset: {data_overview.get('rows', 0):,} rows x {data_overview.get('columns', 0)} columns", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    pdf.set_draw_color(99, 102, 241)
    pdf.set_line_width(1)
    pdf.line(60, pdf.get_y(), 150, pdf.get_y())
    pdf.ln(15)

    # Executive Summary
    pdf.add_section_title("Executive Summary")
    pdf.add_body_text(story.get("executive_summary", "No summary available."))

    # Key Findings
    pdf.add_section_title("Key Findings")
    for i, finding in enumerate(story.get("key_findings", []), 1):
        pdf.add_bullet_point(f"{finding}")

    # Data Quality
    pdf.add_section_title("Data Quality Assessment")
    pdf.add_body_text(story.get("data_quality_story", "No data quality information available."))

    # Patterns and Relationships
    if story.get("patterns_and_relationships"):
        pdf.add_section_title("Patterns & Relationships")
        pdf.add_body_text(story["patterns_and_relationships"])

    # Segmentation Insights
    if story.get("segmentation_insights") and "not" not in story["segmentation_insights"].lower()[:20]:
        pdf.add_section_title("Segmentation Insights")
        pdf.add_body_text(story["segmentation_insights"])

    # Predictive Insights
    if story.get("predictive_insights") and "not" not in story["predictive_insights"].lower()[:20]:
        pdf.add_section_title("Predictive Insights")
        pdf.add_body_text(story["predictive_insights"])

    # Anomalies
    if story.get("anomalies_and_concerns") and "no significant" not in story["anomalies_and_concerns"].lower():
        pdf.add_section_title("Anomalies & Concerns")
        pdf.add_body_text(story["anomalies_and_concerns"])

    # Recommendations
    pdf.add_section_title("Recommendations")
    for rec in story.get("recommendations", []):
        pdf.add_bullet_point(rec)

    # Full Narrative
    pdf.add_page()
    pdf.add_section_title("Data Story Narrative")
    pdf.add_body_text(story.get("story_narrative", ""))

    # Dataset Overview Appendix
    pdf.add_page()
    pdf.add_section_title("Appendix: Dataset Overview")

    overview_text = (
        f"Total Records: {data_overview.get('rows', 0):,}\n"
        f"Total Columns: {data_overview.get('columns', 0)}\n"
        f"Memory Usage: {data_overview.get('memory_usage_mb', 0)} MB\n"
        f"Duplicated Rows Removed: {preprocessing_report.get('duplicates_removed', 0)}\n"
    )
    pdf.add_body_text(overview_text)

    pdf.add_section_title("Column Details")
    col_types = data_overview.get("column_types", {})
    for type_name, cols in col_types.items():
        if cols:
            pdf.add_body_text(f"{type_name.title()} columns ({len(cols)}): {', '.join(cols[:15])}")

    # Save PDF
    output_path = str(REPORTS_DIR / f"{session_id}_report.pdf")
    pdf.output(output_path)
    return output_path
